### ISSUE TITLE
python error: "no module named vls"

### ISSUE THREAD

**Issue by pschimpf** [lionaneesh/RasPod#10]
Running Python 2.7.3 and get the above error, even though:

pi@raspberrypi ~ $ dpkg -s vlc
Package: vlc
Status: install ok installed
Priority: optional
Section: video
Installed-Size: 2883
Maintainer: Debian Multimedia Maintainers pkg-multimedia-maintainers@lists.alioth.debian.org
Architecture: armhf
Version: 2.0.3-5
Replaces: vlc-data (<< 1.1.5), vlc-nox (<< 2.0.2)
Provides: mp3-decoder
...

Any hints would be greatly appreciated!

**Comment by lionaneesh** [comment]
Can you please paste in:
1) The full python log from the point you run the server.
2) Output of "dpkg -s vlc-devel"

**Comment by pschimpf** [comment]
Wow, thanks for the rapid reply lionaneesh!
Should I install vlc-devel with apt-get?
I also just noticed a step in your readme.md: "python setup.py develop" that did not show up in the
setup instructions on the Wiki.  I didn't do that either.

1)
pi@raspberrypi ~ $ python server.py
Traceback (most recent call last):
  File "server.py", line 17, in <module>
    import vlc # libVLC
ImportError: No module named vlc

2)
pi@raspberrypi ~ $ dpkg -s vlc-devel
dpkg-query: package 'vlc-devel' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.

**Comment by pschimpf** [comment]
sorry, didn't mean to close that.

**Comment by pschimpf** [comment]
Sorry, never mind, I was being stupid and got past this.
Looks like I have another issue though, but will post later if I can't solve it.

**Comment by lionaneesh** [comment]
Okay. Sure! Glad to help!
