### ISSUE TITLE
Playback Error

### ISSUE THREAD

**Issue by aaparsan76** [lionaneesh/RasPod#9]
![image](https://f.cloud.github.com/assets/3259301/63087/015cdc42-5db5-11e2-98c1-0e04d5b4f518.png)

Hi,
When I go to click on a song in the web interface, it dosen't play and I get the above error in terminal.

**Comment by lionaneesh** [comment]
First of all, thanks for using RasPod and taking the pain to file a bug report. I appreciate it very much.

Your error report suggests that vlc.Instance() doesn't gets initialized properly. This suggest that you might have not installed the required Vlc and Alsa libraries properly. 

1) Can you please paste in the complete error log, I mean from the point where you run the server.
2) Also, try to run "vlc.py" and paste in the output here? [to verify that you satisfy libVLC's needs]
3) If you get an error in (2) please install the required packages and libraries as specified in the README.

**Comment by lionaneesh** [comment]
The bug reporter won't respond and the bug is not reproducible on my setup. Hence, closing as won't fix.
